title: "Arun's Personal Blog"
author: "Arun Gopichand"
description: "My personal journey and reflections 🌱"

theme: minima

# Navigation menu items
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Journey"
    url: /journey/
  - title: "Contact"
    url: /contact/
