title: "Arun's Personal Blog"
author: "Arun Gopichand"
description: "My personal journey and reflections 🌱"

# Theme
theme: minima

# Blogspot-style features
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/category/:name/'

# Navigation menu
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Journey"
    url: /journey/
  - title: "Contact"
    url: /contact/
